### ISSUE TITLE
报错，设置了enforceActions: false还是报错

### ISSUE THREAD

**Issue by stumpx** [oyb81076/cocos-mobx-tutorial#1]
报错，设置了enforceActions: false还是报错，但是不影响使用
```
[mobx] Deprecated: Deprecated value for 'enforceActions', use 'false' => '"never"', 'true' => '"observed"', '"strict"' => "'always'" instead`
```

**Comment by oyb81076** [comment]
这个是mobx版本的区别，不同的版本设置不一样，
现在版本用
``mobx.configure({ enforceActions: "always" })``
mobx版本其实比较尴尬，5.x版本在低版本的手机微信游览器里运行不了，
在生产环境下，我现在还在用3.5.1这个版本,
在native端不存在问题

**Comment by stumpx** [comment]
看了源码，官方建议设置enforceActions的值时使用'observed'|'always'|'never' 代替 boolean|'strict'才不打印这个错误信息 😅
![image](https://user-images.githubusercontent.com/17932786/45254443-d0946b00-b3aa-11e8-8c69-2550d5a1ed67.png)
