### ISSUE TITLE
报错,使用Mobx。

### ISSUE THREAD

**Issue by Leo501** [oyb81076/cocos-mobx-tutorial#2]
使用本例子时，如果修改了下代码保存后。编辑器会报Since strict-mode is enabled, changing observed observable values outside actions is not allowed。

**Comment by Leo501** [comment]
我现在google到的临时的方式是，把设置@observable的变量不赋值就不报错了。如@observable
    public groundY: number=0;修改成@observable
    public groundY: number就可以了。不知道还有没有更好的方法

**Comment by oyb81076** [comment]
你修改了代码了吗，
mobx 在严格模式下的，修改被@observerable 注解的数值的代码要运行在
@action注解的方法之内，
或者运行在 mobx.runInAction
mobx.reaction
参考https://cn.mobx.js.org/refguide/api.html
``` ts
import {action, observeable} from "mobx"
@ccclass
public A extends cc.Component {
  @observable private groundY = 0;
  @action
  private updateGroundY(){
    this.groundY++;
  }
  protected onLoad(){
    this.schedule(this.updateGroundY, 0.1)
  }
}
```
